version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      androidx:
        patterns: ['androidx.*', 'com.android.*']
      kotlin:
        patterns: ['org.jetbrains.kotlin*']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
